version: '2.0'
services:

    nginx:
        container_name: prod_nginx_ssl
        image: nginx:latest
        ports:
          - "7777:80"
          - "7771:443"
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
          - ./prod-site:/usr/share/nginx/html
          - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem:ro
          - ../volumes/etc/letsencrypt/live/your.site.com/fullchain.pem:/etc/letsencrypt/live/your.site.com/fullchain.pem:ro
          - ../volumes/etc/letsencrypt/live/your.site.com/privkey.pem:/etc/letsencrypt/live/your.site.com/privkey.pem:ro
        networks:
          - docker-network

networks:
    docker-network:
        driver: bridge
